### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by mridah** [roblatour/myarp#1]
I'm trying the following:

![image](https://user-images.githubusercontent.com/21169606/192286586-989e2df4-5ee0-4fb4-9449-51ee070e4185.png)

Microsoft ARP returns all IPs found:

![image](https://user-images.githubusercontent.com/21169606/192286990-22c333d3-5963-42c9-afec-f608474b11d6.png)

How to get the same result along with device names?

**Comment by roblatour** [comment]
download a copy of the setup file from the website:
https://www.rlatour.com/myarp/
the link to the download is near the top of the website, where it says "To download a copy of the program, please click here".

run the setup file, and it will install my arp on your system

once done you can just run it:
c:
cd \
cd "program files"
cd myarp
myarp

device names will populate automatically where they are available.

However,  you can also run it with the database edit option

myarp /DBE

and it will open the database file where you can manually add in descriptions to be displayed as well.

**Comment by roblatour** [comment]
what happens when you enter just:

myarp



________________________________
From: Mridul Ahuja ***@***.***>
Sent: September 26, 2022 1:19 PM
To: roblatour/myarp ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [roblatour/myarp] How to use? (Issue #1)


I'm trying the following:

[image]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F21169606%2F192286586-989e2df4-5ee0-4fb4-9449-51ee070e4185.png&data=05%7C01%7C%7C754792a9884d43b802bc08da9fc1d02c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637997952043155999%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=HVB%2BzB5xZFOgvs%2F5gGDzCzOWO%2FvH%2BHYaNjfVgHtsGKc%3D&reserved=0>

Microsoft ARP returns all IPs found:

[image]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F21169606%2F192286990-22c333d3-5963-42c9-afec-f608474b11d6.png&data=05%7C01%7C%7C754792a9884d43b802bc08da9fc1d02c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637997952043155999%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=BLd7vp1kqggZ1xCTjiMn9rAhS9ZQ50w9aHsSDcxBPMw%3D&reserved=0>

How to get the same result along with device names?
